services:
#    app:

    rabbitmq:
        image: rabbitmq:4.1.4-management
        environment:
            RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/microchat-identify_rabbitmq_cookie
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            labels:
                - traefik.enable=true
                - traefik.swarm.network=microchat-public_net
                - traefik.http.routers.identify-rabbit.rule=Host(`identify-rabbit.microchat`)
                - traefik.http.routers.identify-rabbit.entrypoints=websecure
                - traefik.http.routers.identify-rabbit.tls=true
                - traefik.http.services.identify-rabbit-svc.loadbalancer.server.port=15672
        networks:
            - microchat-public_net
        volumes:
            - microchat-identify_rabbitmq_data:/var/lib/rabbitmq
        configs:
            - source: microchat-identify_rabbitmq_conf
              target: /etc/rabbitmq/rabbitmq.conf
            - source: microchat-identify_rabbitmq_def
              target: /etc/rabbitmq/definitions.json
        secrets:
            - microchat-identify_rabbitmq_cookie
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 20s
            timeout: 5s
            retries: 6

networks:
    microchat-public_net:
        external: true

volumes:
    microchat-identify_rabbitmq_data:
        driver: local

secrets:
    microchat-identify_rabbitmq_cookie:
        external: true

configs:
    microchat-identify_rabbitmq_conf:
        file: ./rabbitmq/rabbitmq.conf
    microchat-identify_rabbitmq_def:
        file: ./rabbitmq/definitions.json
