version: "3.8"

services:
    identify-app:
        build:
            args:
                UID: ${UID}
                GID: ${GID}
            context: ./frankenphp
        container_name: identify-app
        restart: unless-stopped
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            DATABASE_URL: ${DATABASE_URL}
        volumes:
            - ../src:/app:cached
        networks:
            - microchat-identify
            - microchat-public_net
        labels:
            - traefik.enable=true
            - traefik.docker.network=microchat-public_net
            - traefik.http.routers.identify.rule=Host(`${IDENTIFY_DOMAIN}`)
            - traefik.http.routers.identify.entrypoints=websecure
            - traefik.http.routers.identify.tls=true
            - traefik.http.services.identify-svc.loadbalancer.server.port=80

networks:
    microchat-identify:
        driver: bridge

    microchat-public_net:
        external: true
